### ISSUE TITLE
ACCURACY

### ISSUE THREAD

**Issue by zxs1995** [zackhy/TextClassification#4]
may I ask you what is the accuracy of your implementation ,please

**Comment by zxs1995** [comment]
may I ask you what the accuracy of your implementation is ,please.

**Comment by zackhy** [comment]
@zxs1995 accuracy = number of correct predictions / all predictions

**Comment by FajarSukma** [comment]
i have try to run test.py but i got this error


```
(tf15) E:\Fajar\Programming\Python\Deep Learning\TextClassification\TextClassification-master>python test.py --test_data_file=./data/data.csv --run_dir=./runs/1530085310/ --checkpoi
nt=clf-10000

C:\Users\FajarSukma\Anaconda3\envs\tf15\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprec
ated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Building dataset ...
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    shuffle=False)
  File "E:\Fajar\Programming\Python\Deep Learning\TextClassification\TextClassification-master\data_helper.py", line 38, in load_data
    sw = _stop_words(sw_path)
  File "E:\Fajar\Programming\Python\Deep Learning\TextClassification\TextClassification-master\data_helper.py", line 149, in _stop_words
    with open(path, 'r', encoding='utf-8') as f:
TypeError: expected str, bytes or os.PathLike object, not Flag
```

Could you help me,please?

**Comment by zackhy** [comment]
@FajarSukma If you don't have a stop word file, try assigning the sw_path at line 33 to None and see if this works.
